import {App} from "vue";
import InputText from "primevue/inputtext";
import InputMask from "primevue/inputmask";
import FloatLabel from "primevue/floatlabel";
import InputNumber from "primevue/inputnumber";
import InputOtp from "primevue/inputotp";
import InputSwitch from "primevue/inputswitch";
import Calendar from "primevue/calendar";
import Password from "primevue/password";
import Button from "primevue/button";
import Dock from "primevue/dock";
import Avatar from "primevue/avatar";
import Menu from "primevue/menu";
import TabMenu from "primevue/tabmenu";
import Dropdown from "primevue/dropdown";
import Paginator from "primevue/paginator";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import SplitButton from "primevue/splitbutton";
import Sidebar from "primevue/sidebar";
import Dialog from "primevue/dialog";
import MultiSelect from "primevue/multiselect";
import ConfirmDialog from "primevue/confirmdialog";
import SelectButton from "primevue/selectbutton";
import InputGroup from "primevue/inputgroup";
import InputGroupAddon from "primevue/inputgroupaddon";
import StepperPanel from "primevue/stepperpanel";
import Stepper from "primevue/stepper";
import Chart from "primevue/chart";
import ContextMenu from 'primevue/contextmenu';
import Slider from 'primevue/slider';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import Checkbox from "primevue/checkbox";
import RadioButton from "primevue/radiobutton";
import Galleria from "primevue/galleria";
import Carousel from "primevue/carousel";
import Image from 'primevue/image';
import Card from "primevue/card";
import SpeedDial from "primevue/speeddial";
import Textarea from "primevue/textarea";
import MeterGroup from "primevue/metergroup";
import DynamicDialog from 'primevue/dynamicdialog';
import Editor from "primevue/editor";
import IconField from "primevue/iconfield";
import InputIcon from "primevue/inputicon";
import ToastService from "primevue/toastservice";
import ConfirmationService from "primevue/confirmationservice";
import DialogService from 'primevue/dialogservice';
import AutoComplete from "primevue/autocomplete";
import ToggleButton from 'primevue/togglebutton';
import PickList from 'primevue/picklist';
import Listbox from 'primevue/listbox';
import Tooltip from 'primevue/tooltip';
import Badge from 'primevue/Badge';
import Tag from "primevue/tag";
import Chip from "primevue/chip";
import ColumnGroup from 'primevue/columngroup';
import Row from 'primevue/row';
import DataView from "primevue/dataview";
import Skeleton from 'primevue/skeleton';


const primevue = (app: App<Element>) => {
    app.component("InputText", InputText);
    app.component("InputMask", InputMask);
    app.component("FloatLabel", FloatLabel);
    app.component("InputNumber", InputNumber);
    app.component("InputSwitch", InputSwitch);
    app.component("Calendar", Calendar);
    app.component("Password", Password);
    app.component("Button", Button);
    app.component("Dock", Dock);
    app.component("Avatar", Avatar);
    app.component("Menu", Menu);
    app.component("TabMenu", TabMenu);
    app.component("Dropdown", Dropdown);
    app.component("Paginator", Paginator);
    app.component("DataTable", DataTable);
    app.component("DataView", DataView);
    app.component("Column", Column);
    app.component("SplitButton", SplitButton);
    app.component("Sidebar", Sidebar);
    app.component("Dialog", Dialog);
    app.component("MultiSelect", MultiSelect);
    app.component("ConfirmDialog", ConfirmDialog);
    app.component("SelectButton", SelectButton);
    app.component("InputGroup", InputGroup);
    app.component("InputGroupAddon", InputGroupAddon);
    app.component("InputOtp", InputOtp);
    app.component("Chart", Chart);
    app.component("StepperPanel", StepperPanel);
    app.component("Stepper", Stepper);
    app.component("ContextMenu", ContextMenu);
    app.component("Slider", Slider);
    app.component("TabPanel", TabPanel);
    app.component("TabView", TabView);
    app.component("Checkbox", Checkbox);
    app.component("RadioButton", RadioButton);
    app.component("Galleria", Galleria);
    app.component("Carousel", Carousel);
    app.component("Image", Image);
    app.component("Card", Card);
    app.component("SpeedDial", SpeedDial);
    app.component("Textarea", Textarea);
    app.component("MeterGroup", MeterGroup);
    app.component("DynamicDialog", DynamicDialog);
    app.component("AutoComplete", AutoComplete);
    app.component("ToggleButton", ToggleButton);
    app.component("Editor", Editor);
    app.component("IconField", IconField);
    app.component("InputIcon", InputIcon);
    app.component("PickList", PickList);
    app.component("Listbox", Listbox);
    app.component("Badge", Badge);
    app.component("Tag", Tag);
    app.component("Chip", Chip);
    app.component("ColumnGroup ", ColumnGroup );
    app.component("Row", Row);
    app.component("Skeleton", Skeleton);

    app.use(ToastService);
    app.use(DialogService);
    app.use(ConfirmationService);
    app.directive('tooltip', Tooltip);

};

export default primevue;
